### ISSUE TITLE
Open Source License

### ISSUE THREAD

**Issue by IanTheEngineer** [XRobots/openDog#2]
Hi James! I'm thrilled to see your new project open-sourced on github. I have already played around a bit with your model, doing a very rudimentary port of it into [URDF format](http://wiki.ros.org/urdf) and displaying it in RViz, ROS' visualization tool: https://github.com/IanTheEngineer/opendog_robot

It occurred to me while working with your models, that there isn't a license for your work. Without an open source license, it's not clear who can utilize, modify, and redistribute opendog, and how credit should be attributed to you. I'd recommend choosing a license, adding your copyright to it, and placing it in the openDog repository to be distributed with your code and models:

https://choosealicense.com/

For what it's worth, the licenses for code distributed the ROS ecosystem are typically permissive licenses like BSD, MIT, or Apache 2.0: http://wiki.ros.org/DevelopersGuide#Licensing

**Comment by jantje** [comment]
If I understood correctly from james his video the licence is GNU GPLv3

**Comment by XRobots** [comment]
@IanTheEngineer looks great - I should really take the time to learn about ROS, but maybe I will once basic functionality is there.

I'm probably re-drawing the whole thing though from the feel up as I actually design the detail of where bearings and hinges etc go, although it's the same overall concept.

@jantje @IanTheEngineer yes the license is 'true open source' so anyone can modify and commercialise   the design if they wish - same as RapRap 3D printers. I think GPL3 fits as that's what Lulzbot are using for printer hardware and software: https://www.lulzbot.com/learn/tutorials/licensing-recommendations

Also they have a copyright license, which is I guess for the 'likeness' of the printer since that should only cover creative works?.

Obviously Creative Commons licensing is used a lot on Thingiverse , but my understanding is that a copyright license can't cover functionality unless it's inherent in the look of it.

**Comment by jantje** [comment]
I hate licences so I'm not the specialist but if I understood correctly you want people that modify the code to share their modifications. In that case (based on the link above) GNU GPLv3 is the way to go

**Comment by IanTheEngineer** [comment]
> I hate licences so I'm not the specialist 

I agree with the sentiment that the license shouldn't matter, but rather just the contribution to open source itself. Alas, [no license is in fact a license only to the original author](https://choosealicense.com/no-permission/), which is generally avoided by the open source community.

> yes the license is 'true open source' so anyone can modify and commercialise the design if they wish - same as RapRap 3D printers. I think GPL3 fits...

I think your assessment that GPL3 is a better fit than Creative Commons for this CAD/software hybrid project is a good one. There are plenty of open source software projects in the world using GPL3, and Creative Commons itself [recommends against](https://creativecommons.org/faq/#can-i-apply-a-creative-commons-license-to-software) using their license for software.

> I should really take the time to learn about ROS, but maybe I will once basic functionality is there.

I would be happy to help in your efforts to learn ROS, and add it to your robots. I've been using it for years in grad school, professionally, and as a hobbyist. Most recently, I emulated my employer's [robot arm using Gazebo](https://github.com/RethinkRobotics/sawyer_simulator) for educators & researchers. The learning curve is unfortunately a bit steep, but the rewards are substantial: robotics math toolkits, pre-calculated transforms, path planning algorithms, physics simulators, inter-process communication, sensor drivers, etc. Plus a robust open source community :) 

Feel free to contact me via email ian@ianthe.engineer whenever you're ready to dive into ROS.

**Comment by XRobots** [comment]
Thanks @IanTheEngineer  I've added a statement to say 'All CAD and code is licensed under GPL3: https://www.gnu.org/licenses/gpl-3.0.en.html' in each README for RObotX and openDog.

**Comment by rjw57** [comment]
That's great, @XRobots, I'll open a PR which adds a "COPYING" file to the repo. Then GitHub will mark the repo as being GPL3.

**Comment by rjw57** [comment]
@XRobots PR open at #4.
